### ISSUE TITLE
Training on CUDA devices fails when PyTorch doesn't have CUDA enabled

### ISSUE THREAD

**Issue by scog1234** [robin-janssen/CODES-Benchmark#1]
Since the default configuration uses CUDA devices for training, it would be helpful if the code would check at install time whether the user has a version of PyTorch with CUDA enabled, and warned the user if this wasn't the case.

**Comment by robin-janssen** [comment]
Made some error handling for this case in https://github.com/robin-janssen/CODES-Benchmark/commit/9b098e6423f611e27b065b5d08cf350c3884bfc4. During installation, pytorch should automatically install the cuda version if cuda is available and the cpu-only version otherwise.
