### ISSUE TITLE
Documentation doesn't explain how to add your own dataset to the repository

### ISSUE THREAD

**Issue by scog1234** [robin-janssen/CODES-Benchmark#2]
The documentation describes how to create a new dataset in the CODES format, but not how to actually add this to the public repository. (I assume the planned workflow is (a) upload to zenodo, (b) add an appropriate entry to data_sources.yaml ?)

**Comment by robin-janssen** [comment]
Thanks for the heads up!
The documentation was now updated accordingly (253eb220d681a0258b409864aa5de91c6fafad84). If you want to make a dataset publicly available, the idea is indeed to upload it on Zenodo (could also be a different platform that provides a direct-download URL) and add the URL to data_sources.yaml. The benchmark will also work with purely local data that is not shared with others.

**Comment by robin-janssen** [comment]
Thanks for the heads up!
The documentation was now [updated accordingly](https://github.com/Immi000/CODES-Benchmark-Docs/commit/253eb220d681a0258b409864aa5de91c6fafad84). If you want to make a dataset publicly available, the idea is indeed to upload it on Zenodo (could also be a different platform that provides a direct-download URL) and add the URL to data_sources.yaml. The benchmark will also work with purely local data that is not shared with others.
